services:
  - type: web
    name: quiz-app-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishDir: build
    envVars:
      - key: NODE_ENV
        value: production