services:
  - type: web
    name: quiz-app-frontend
    env: static
    buildCommand: npm install react-scripts -g && npx react-scripts build
    staticPublishDir: build
    envVars:
      - key: NODE_ENV
        value: production