services:
  # Backend service
  - type: web
    name: quiz-app-backend
    runtime: docker
    repo: https://github.com/ShivamYadavlit/Quiz-App-Springboot-Shivam-Y-Yadav.git
    plan: free
    region: oregon
    rootDir: backend
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        value: mongodb+srv://shivamyadav2072000_db_user:3zLn63QvMRUkWqDl@cluster0.4emwg3d.mongodb.net/quiz_app_db?retryWrites=true&w=majority&appName=Cluster0
      - key: MONGODB_DATABASE
        value: quiz_app_db
      - key: JWT_SECRET
        value: mySecretKey123456789012345678901234567890123456789012345678901234567890
      - key: JWT_EXPIRATION
        value: 86400000
      - key: CORS_ALLOWED_ORIGINS
        value: http://localhost:3000,https://quiz-app-frontend.onrender.com,https://quiz-app-sp-frontend.onrender.com
      - key: ADMIN_SECRET_KEY
        value: YourCustomSecretKey2024!

  # Frontend service
  - type: static
    name: quiz-app-frontend
    runtime: static
    repo: https://github.com/ShivamYadavlit/Quiz-App-Springboot-Shivam-Y-Yadav.git
    plan: free
    region: oregon
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: NODE_ENV
        value: production
    domains:
      - quiz-app-frontend.onrender.com